## Multiple Linear Regression

In [23]:
#import libraries
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt


In [3]:
# import data set
df = pd.read_csv('DailyDelhiClimateTrain.csv')
df.head(5) 

date   meantemp   humidity  wind_speed  meanpressure
0  1/1/2013  10.000000  84.500000    0.000000   1015.666667
1  1/2/2013   7.400000  92.000000    2.980000   1017.800000
2  1/3/2013   7.166667  87.000000    4.633333   1018.666667
3  1/4/2013   8.666667  71.333333    1.233333   1017.166667
4  1/5/2013   6.000000  86.833333    3.700000   1016.500000

In [4]:
# checking for null data.
df.isnull().sum()

date            0
meantemp        0
humidity        0
wind_speed      0
meanpressure    0
dtype: int64

In [29]:
X = df[['meantemp','humidity','wind_speed']]
y = df['meanpressure']

In [30]:
X.head(5)

meantemp   humidity  wind_speed
0  10.000000  84.500000    0.000000
1   7.400000  92.000000    2.980000
2   7.166667  87.000000    4.633333
3   8.666667  71.333333    1.233333
4   6.000000  86.833333    3.700000

In [31]:
y.head(5)

0    1015.666667
1    1017.800000
2    1018.666667
3    1017.166667
4    1016.500000
Name: meanpressure, dtype: float64

In [32]:
df.dtypes

date             object
meantemp        float64
humidity        float64
wind_speed      float64
meanpressure    float64
dtype: object

In [33]:
# create & fit your model
model = LinearRegression().fit(X,y)
model

LinearRegression()

In [34]:
model.coef_

array([-1.31985589, -0.38242163, -0.69084763])

In [35]:
model.intercept_

1072.6946636013752

In [37]:
model.predict([[10.000000,84.500000,0.000000]])

c:\Users\Administrator\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([1027.18147719])

In [ ]:
# Assignment is how to plot multiple linear reg model?
# How to test the efficacy of model?


In [38]:
# import library and split data 
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=1/5,random_state=0)

In [39]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model=model.fit(X_train,y_train)
model

LinearRegression()

In [50]:
print('Score for Training data ',model.score(X_train,y_train))
print('Score for Testing data',model.score(X_test,y_test))

Score for Training data  0.0019037808193672623
Score for Testing data 0.02156287295739856


In [43]:
model.predict([[15.91304348,85.86956522,2.743478261]])

c:\Users\Administrator\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([1018.27890184])