# Numpy
- here we are axploring numpy(numeric python) which is 1d,2d, and ndarray. 
- np.zero,np.emplty,np.ones,np. np.array,np.arange,np.linespace,,dtype
-  lets explore concatenation in array.


In [9]:
import numpy as np
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x,y),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

# Shape, size, dimentions of an array

In [17]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [12]:
array_example.ndim

3

In [13]:
array_example.size

24

In [18]:
array_example.shape


(3, 2, 4)

# Array reshape

In [30]:
a= np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [44]:
b= a.reshape(3,2,2)
b

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [46]:
b

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

   # How to convert a 1D array into a 2D array (how to add a new axis to an array)

In [48]:
a= np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [49]:
a.shape

(12,)

In [50]:
a2= a[np.newaxis,:]

In [51]:
a2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [52]:
a2.shape

(1, 12)

In [84]:
a3=a2[np.newaxis,:]

In [86]:
a3.shape

(1, 1, 12)

In [85]:
print(a3)

[[[ 0  1  2  3  4  5  6  7  8  9 10 11]]]


In [129]:
a4= a[-11:,np.newaxis]

In [136]:
a4.repeat(6/2+1)

array([ 1,  1,  1,  1,  2,  2,  2,  2,  3,  3,  3,  3,  4,  4,  4,  4,  5,
        5,  5,  5,  6,  6,  6,  6,  7,  7,  7,  7,  8,  8,  8,  8,  9,  9,
        9,  9, 10, 10, 10, 10, 11, 11, 11, 11])

# np.expand_dims

In [154]:
a=np.arange(12)

In [155]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [156]:
a.shape

(12,)

In [161]:
b= np.expand_dims(a,axis=0)
b.shape
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [163]:
b.shape

(1, 12)

In [166]:
b= np.expand_dims(a,axis=1)
b.shape
b

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

# Indexing and Slicing

In [168]:
data = np.arange(1,4)
data

array([1, 2, 3])

In [170]:
data[0]

1

In [176]:
data[-2:]

array([2, 3])

In [182]:
data[0:3]

array([1, 2, 3])

In [196]:
a= np.arange(1,13)

In [197]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [198]:
a.shape

(12,)

In [201]:
b=a.reshape(3,4)

In [202]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [204]:
print(b[b<5])

[1 2 3 4]


In [209]:
more_tfive=(b>4)

In [212]:
c=(b[more_tfive])
c.reshape(4,2)

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

# with operators

In [217]:
divi_by_2 = b[b%2==0]
print(divi_by_2)

[ 2  4  6  8 10 12]


In [218]:
d= a[(a>3)&(a<11)]
d

array([ 4,  5,  6,  7,  8,  9, 10])

In [223]:
d= (b>5)|(b==5)
print(d)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [227]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [233]:
c= np.nonzero(b<5)
print(c)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


# How to  create new array from existing data


In [239]:
a= np.arange(1,12)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11]


In [242]:
b=a[3:7]
print(b)

[4 5 6 7]


In [243]:
print(a,b)

[ 1  2  3  4  5  6  7  8  9 10 11] [4 5 6 7]


# Array Stacking 

In [245]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [246]:
print(a1,a2)

[[1 1]
 [2 2]] [[3 3]
 [4 4]]


In [248]:
c= np.vstack((a1,a2))
print(c)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [250]:
d= np.hstack((a1,a2))
print(d)

[[1 1 3 3]
 [2 2 4 4]]


# creating matrices

In [251]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [252]:
data.max()

6

In [253]:
data.min()

1

In [254]:
data.sum()

21

In [269]:
data[0:3]

array([[1, 2],
       [3, 4],
       [5, 6]])

In [270]:
data[0,1]

2

In [271]:
data[1,1]

4

In [272]:
data[1:3]

array([[3, 4],
       [5, 6]])

 # Agregate

In [273]:
data.max(axis=0)

array([5, 6])

In [274]:
data.max(axis=1)

array([2, 4, 6])

# flip an array

In [275]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [276]:
rev_array = np.flip(a)

In [277]:
rev_array

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [278]:
a = np.array([1, 2, 3, 4, 5, 6])
a?

In [279]:
np.empty(5)

array([1.12230046e-311, 4.67296746e-307, 1.69121096e-306, 1.12236245e-311,
       1.12236246e-311])

In [282]:
np.ones(5)

array([1., 1., 1., 1., 1.])

# 3-D array aka Tensor

In [312]:
a=np.array([[[1,2,0,0],[4,5,0,1],[2,3,0,2],[1,5,0,3]],
           [[2,2,1,0],[4,5,1,1],[2,3,1,2],[2,5,1,3]],
          [[3,2,2,0],[4,5,2,1],[2,3,2,2],[3,5,2,3]],
          [[4,2,3,0],[4,5,3,1],[2,3,3,2],[4,5,3,3]]])

In [314]:
a.shape

(4, 4, 4)

In [318]:
a[3,0]

array([4, 2, 3, 0])

In [323]:
a[0:1]

array([[[1, 2, 0, 0],
        [4, 5, 0, 1],
        [2, 3, 0, 2],
        [1, 5, 0, 3]]])